source :rubygems

gem 'thin'
gem 'pg'
gem 'rake'
gem 'sinatra', '~> 1.3.1'
gem 'sinatra-reloader'
gem 'haml'
gem 'sass'
gem 'oa-oauth', '>= 0.2.3'
gem 'yajl-ruby'
gem 'mogli', '~> 0.0.36'
gem 'createsend'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'json'
gem 'newrelic_rpm'