source :rubygems

gem 'rake'
gem 'sinatra', '>= 1.0'
gem 'sinatra-reloader', '>= 0.5.0'
gem 'haml'
gem 'sass'
gem 'oa-oauth', '>= 0.2.3'
gem 'yajl-ruby'
gem 'mogli', '~> 0.0.36'
gem 'createsend'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'json'
